version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/var/lib/localstack
    networks:
      - mynetwork

  s3-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - cloud.aws.s3.endpoint=http://localstack:4566
    depends_on:
      - localstack
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
